"""
Regenerates the Israeli holiday table used by the trends and production code.

    pip install pyluach
    python3 tools/generate_holidays.py 2024 2032 > /tmp/holidays.py
    # then replace the IL_HOLIDAYS block in backend/main.py

kinds: chag = holiday (most shops closed), erev = the day before (the big
shopping day), period = chol hamoed / Hanukkah / Purim (unusual days).
Independence Day follows the moving rule (Friday/Saturday -> Thursday,
Monday -> Tuesday). Spot-check a few dates against a published calendar
before shipping a new table.
"""
import datetime
import sys

from pyluach import dates

CHAG = {"א׳ ראש השנה": "ראש השנה", "ב׳ ראש השנה": "ראש השנה", "יום כיפור": "יום כיפור",
        "א׳ סוכות": "סוכות", "שמיני עצרת": "שמחת תורה", "א׳ פסח": "פסח",
        "ז׳ פסח": "שביעי של פסח", "שבועות": "שבועות"}
PERIOD = {"סוכות": "חול המועד סוכות", "פסח": "חול המועד פסח", "חנוכה": "חנוכה",
          "פורים": "פורים", "שושן פורים": "פורים"}


def build(first_year, last_year):
    out = {}
    d = datetime.date(first_year, 1, 1)
    end = datetime.date(last_year, 12, 31)
    while d <= end:
        h = dates.GregorianDate(d.year, d.month, d.day).to_heb()
        n = h.holiday(israel=True, hebrew=True, prefix_day=True)
        if n in CHAG:
            out[d] = ("chag", CHAG[n])
        elif n:
            base = n.split(" ", 1)[1] if n[1:2] == "׳" and " " in n else n
            if base in PERIOD and d not in out:
                out[d] = ("period", PERIOD[base])
        if h.month == 2 and h.day == 5:            # 5 Iyar, Independence Day
            w = d.weekday()
            t = d - datetime.timedelta(days=1) if w == 4 else (
                d - datetime.timedelta(days=2) if w == 5 else (
                    d + datetime.timedelta(days=1) if w == 0 else d))
            out[t] = ("chag", "יום העצמאות")
        d += datetime.timedelta(days=1)
    # the day before every holiday is an eve, even inside chol hamoed
    for day, (kind, name) in sorted(out.items()):
        if kind == "chag":
            prev = day - datetime.timedelta(days=1)
            if out.get(prev, ("", ""))[0] != "chag":
                out[prev] = ("erev", "ערב " + name)
    return out


if __name__ == "__main__":
    a = int(sys.argv[1]) if len(sys.argv) > 1 else 2024
    b = int(sys.argv[2]) if len(sys.argv) > 2 else 2032
    table = build(a, b)
    print("# Generated by tools/generate_holidays.py (pyluach, Israel), %d-%d." % (a, b))
    print("# Independence Day follows the moving rule; dates spot-checked against")
    print("# calendar.2net.co.il for 2025-2027. Re-run the tool to extend the range.")
    print("IL_HOLIDAYS = {")
    for k in sorted(table):
        print('    "%s": ("%s", "%s"),' % (k.isoformat(), table[k][0], table[k][1]))
    print("}")
